### ISSUE TITLE
How you managed to get flag3?

### ISSUE THREAD

**Issue by ron-zano** [testerting/hacker101-ctf#2]
It seems just like a random number... how did you get to 945?
btw thanks for the writeup :)

**Comment by testert1ng** [comment]
Hi @ba2sik 

For [Postbook flag3](https://github.com/testerting/hacker101-ctf/blob/f644c9324f8d035f7528a49a15443d6bec2bb194/postbook/flag3/README.md), I did not get it first.

But the hint for flag3 is **189 * 5**, which equals 945

For this flag, I think the point is letting us to scan any possible variables although there is nothing between id 10 to 945. If you scan the id thousands of times, you may get it.

Cheers

**Comment by ron-zano** [comment]
> Hi @ba2sik
> 
> For [Postbook flag3](https://github.com/testerting/hacker101-ctf/blob/f644c9324f8d035f7528a49a15443d6bec2bb194/postbook/flag3/README.md), I did not get it first.
> 
> But the hint for flag3 is **189 * 5**, which equals 945
> 
> For this flag, I think the point is letting us to scan any possible variables although there is nothing between id 10 to 945. If you scan the id thousands of times, you may get it.
> 
> Cheers

Oh ok, Thanks :)
btw, In my opinion, a challenge like this doesn't really test thinking/ability, because they could also just throw a higher random number and then no one would discover it without clue.

**Comment by testert1ng** [comment]
@ba2sik, 

It is more like a thinking or ability to fuzz testing all the possible point and attention to details.

Btw, this is the last flag I found in this challenge. Really an abnormal flag!

Happy hunting the rest of flags :)
