### ISSUE TITLE
query Postbook flag3 189*5=945

### ISSUE THREAD

**Issue by harshinsecurity** [testerting/hacker101-ctf#3]
in this ctf how did you know that that id can be changed upto 189*5=945 without using the burpsuit or like tools?

**Comment by testert1ng** [comment]
Hi @harsh-kk ,

Actually no idea. Or just by checking the hints? 

This Flag trapped me for a long time.

Cheers,
@testerting

**Comment by glaucusec** [comment]
> in this ctf how did you know that that id can be changed upto 189*5=945 without using the burpsuit or like tools?

Do you have any updates? How can someone guess this?
