### ISSUE TITLE
Micro CMS v2 - Flag 1

### ISSUE THREAD

**Issue by K4PT41N** [testerting/hacker101-ctf#6]
I use curl to make a POST request to the edit/2 url ,but it says that the method is not allowed.Does this happen because I am using Windows?

**Comment by testert1ng** [comment]
Hi @Patrick5088 

Windows should not be a problem. I just tried for this flag.

Did you put the correct url which is something like `/page/edit/2`

Cheers,
@testerting

**Comment by K4PT41N** [comment]
Hello

Thank you for responding,
![image](https://user-images.githubusercontent.com/7592885/75707313-5b67d480-5cc7-11ea-9618-6a6dbf4ec2f5.png)

Yes , I copied the url while on edit mode on the page.I used command prompt (with admin priviledges). I used the curl command ,with the right parameters -v -X and -POST and the server responded by saying that the method was not allowed.I thought this was something random ,so I tried all the HTTP request methods.Same response.

Regards,
@Patrick5088

**Comment by testert1ng** [comment]
Hi @Patrick5088 

You used `-POST` instead of `POST`.  That is why the request is not allowed. 

Here is the correct syntax

```
curl -X POST http://host/hash/page/edit/2
```
