### ISSUE TITLE
Solution to photo gallery flag 2 doesn't seem to work anymore

### ISSUE THREAD

**Issue by tokyotribe** [testerting/hacker101-ctf#8]
I'm getting 500 error on the last step, even with .txt used, so don't know if the txt file is not correctly created, or if the last step is unable to display the txt file. Does this still work for you?

**Comment by testert1ng** [comment]
Hey @tokyotribe 

Can you tell me which Challenge are you talking about?

**Comment by tokyotribe** [comment]
Sorry, it was the solution to Petshop pro

**Comment by tokyotribe** [comment]
Sorry, it was the solution to Photo Gallery - FLAG2

**Comment by testert1ng** [comment]
![image](https://user-images.githubusercontent.com/32080604/80281842-62ecac80-8751-11ea-8d26-dfa0afc57458.png)

As the command exports the **env** variable to **test** without an extension. It should be nothing related to **txt**. What did you use when doing the exercise? Can you provide more detail?

**Comment by testert1ng** [comment]
Hi @tokyotribe 

Ok, I see what is the problem. Please wait a minute and I will push an fix for that.

**Comment by tokyotribe** [comment]
That worked! Thanks!
I also didn't realise you had to visit index page to execute the command (missed that earlier), but you made it clearer now too.
Thanks a lot for your work on these solutions. They really helped me learn!

**Comment by testert1ng** [comment]
All trick is in the main.py you have got from flag0. 

The fetch route only store the command into sql.  And the index page fetched the command and executed it. That is where the file created.
